tupla = ('RS', 'SC', 'PR', 'SP', 'RJ', 'ES', 'MG')
print(tupla)
print('='*42)
print(f'Os 3 primeiros são: {tupla[:3]}')
print(f'O último é: {tupla[-1]}')
print(f'O Paraná está na {tupla.index("PR") +1}° posição')
